# Generated by Django 4.2.2 on 2023-06-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
