# Generated by Django 4.2.2 on 2023-06-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_urlFalse',
            new_name='image_url',
        ),
    ]
